### ISSUE TITLE
Does local control via Homa Assistant work working now in Poland?

### ISSUE THREAD

**Issue by atomic339** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#169]
I heard about problem with local API control. I would like to buy somfy tahoma switch but is a problem with local is actual?

**Comment by llavorel-somfy** [comment]
Hi @atomic339 

Problems to use the developer mode have been addressed in February T

**Comment by AdrianEddy** [comment]
@llavorel-somfy I still have the local API connection issues after reboot, firmware 1.29. Port 8443 is closed after reboot
I'm in Poland too

**Comment by llavorel-somfy** [comment]
Hello @AdrianEddy 

I believe that @atomic339 was mentionning another issue as we faced a major issue on the devMode after the January firmware release : https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/161
